# Input/Output
input: null    # Path to the input VCF file
output: null   # Directory to store output files
db_bcf: null   # Path to the database BCF file

# Resource files
chr_add: '/mnt/data/samples/chr_add.txt'
reference: '/mnt/data/resources/reference/ucsc/hg19_canonical.fa.gz'
vep_cache: '/mnt/data/apps/ensembl-vep/113/cachedir/'

# VEP Configuration
vep_assembly: 'GRCh37'
vep_options:
  - '--transcript_version'
  - '--total_length'
  - '--flag_pick'
  - '--exclude_predicted'
  - '--hgvs'
  - '--hgvsg'
  - '--spdi'
  - '--variant_class'
  - '--uniprot'
  - '--gene_version'
  - '--protein'
  - '--symbol'
  - '--canonical'
  - '--appris'
  - '--mane'
  - '--biotype'
  - '--domains'
  - '--gencode_basic'

# VEP Performance Settings
vep_max_chr_parallel: 2
vep_max_forks: 2

# Tool paths and container settings
container_engine: '/usr/bin/apptainer'
container_bind: '-B /mnt/data:/mnt/data'
vep_container: '/mnt/data/apps/ensembl-vep/113/vep.sif'
echtvar_path: '/mnt/data/apps/echtvar/echtvar'

# Workflow control
db_mode: false